# Data Sources

## Field phenotyping research sites

### Maricopa Agricultural Center \(MAC\), Arizona

The Maricopa field site is located at the the University of Arizona Maricopa Agricultural Center and USDA Arid Land Research Station in Maricopa, Arizona. At this site, we have deployed the following phenotyping platforms.

* The [**Lemnatec Scanalyzer Field System**](http://www.lemnatec.com/products/hardware-solutions/scanalyzer-field/) is the largest field crop analytics robot in the world. This high-throughput phenotyping field-scanning robot has a 30-ton steel gantry that autonomously moves along two 200-meter steel rails while continuously imaging the crops growing below it with a diverse array of cameras and sensors.

## Lemnatec Field Sensors

| Description | Camera | Field of View | Technical Data |
| :--- | :--- | :--- | :--- |
| Hyperspectral Imager | [Inspector VNIR](http://www.headwallphotonics.com/spectral-imaging/hyperspectral/vnir) | 21° | 380-1000 nm @ 2/3 nm resolution |
| Hyperspectral Imager | [Inspector SWIR](http://www.headwallphotonics.com/spectral-imaging/hyperspectral/swir) | 44.5° | 900-2500 nm @ 12 nm resolution |
| Thermal Infrared | [FLIR SC 615](http://www.flir.com/automation/display/?id=41330) | 25° x 19° | Thermal Sensitivity &lt; 50mK @ 30C |
|  |  |  | Range: -40 to 150 C |
| Dedicated NDVI \(1 down, 1 up\) | [Skye Multispectral Radiometer](http://www.skyeinstruments.com/news-events/new-spectral-albedometers/) |  | CH1: 650 +/- 3nm |
|  |  |  | CH2: 800 +/- 3nm |
|  |  |  | Bandwidth: 10nm +/- 3nm |
| Dedicated PRI Sensor | [Skye Radiometer](http://www.skyeinstruments.com/products/light-sensors-systems/light-sensor-range/new-ndvipri-sensor/) |  | CH1: 531nm +/- 3nm |
| PRI = [Photochemical Reflectance Index](https://en.wikipedia.org/wiki/Photochemical_Reflectance_Index) |  |  | CH2: 570 +/- 3nm |
|  |  |  | Bandwidth: 10nm +/- 3nm |
| PAR Sensor | [Quantum SQ-300](http://www.apogeeinstruments.com/quantum/) | 180° | Spectral Range 410 to 655 nm |
| VNIR Spectrometer \(downwelling radiance\) | [Ocean Optics STS-Vis](http://oceanoptics.com/product/sts-vis-microspectrometer/) |  | Range: 337-824 nm @ 1/2 nm |
| SWIR Spectrometer \(downwelling radiance\) | [Ocean Optics STS-Vis](http://oceanoptics.com/product/sts-vis-microspectrometer/) |  | 800-2500 nm |
| Laser Scanner| [Custom Frauhofer 3D](http://www.ipm.fraunhofer.de/en/bu/object-shape-detection/technologies/mobile-laser-scanning.html) | 0.5m width | Resolution: 0.3-0.9 mm |
| Stereo RGB Cameras | [GT3300 C](http://www.1stvision.com/cameras/AVT/Prosilica-GT3300-B-C.html) | 53° |  |
| Active Reflectance | [Crop Circle ACS430P](http://hollandscientific.com/product/crop-circle-acs-430-active-crop-canopy-sensor/) |  | Bands: 670, 730, 780 nm |
| Fluorescence Measurement | [Lemnatec PSII](http://www.lemnatec.com/products/imaging-modules/psii-imaging/) | 25° x 19° | PSII Fluorescence Response |
|  |  |  | Source: 635nm x 4000umol/m2/s |
| Environmental Sensors | [Thies ClimaSensorD](http://www.thiesclima.com/ClimaSensorUS_e.html) |  | Wind, Air T, Humidity |
|  |  |  | Pressure, Light, Precipitation |
| Open Path CO2 Sensor | [GMP 343](http://www.vaisala.com/en/products/carbondioxide/Pages/GMP343.aspx) |  | Range: 0-1000 ppm |

* The **PhenoTractor** is fitted with a sensor frame that supports a real time kinematic \(RTK\) satellite navigation antenna, a sonar transducer,  an infrared temperature \(IRT\) scanner, and three [GreenSeeker crop sensing systems](http://www.trimble.com/agriculture/greenseeker.aspx).
* **UAV** data: weekly flights with RGB and multispectral cameras
* **Manually Collected Field Data** - Data will are collected manually using standard field methods. These measurements are used to calibrate and validate phenotypes derived from sensor-collected data.

## Controlled-environment phenotyping

#### Donald Danforth Plant Science Center, Missouri

The [Bellwether Foundation Phenotyping Facility](https://www.danforthcenter.org/scientists-research/core-technologies/phenotyping) is a climate controlled 70 m2 growth house with a conveyor belt system for moving plants to and from fluorescence, color, and near infrared imaging cabinets. This automated, high-throughput platform allows repeated non-destructive time-series image capture and multi-parametric analysis of 1,140 plants in a single experiment.

## Genomics

Genomic data includes whole-genome resequencing data from the HudsonAlpha Institute for Biotechnology, Alabama for 384 samples for accessions from the sorghum Bioenergy Association Panel \(BAP\) and genotyping-by-sequencing \(GBS\) data from Kansas State University for 768 samples from a population of sorghum recombinant inbred lines \(RIL\).

