# Data Use Policy

## Release with Attribution

We plan to make data from the Transportation Energy Resources from Renewable Agriculture Phenotyping Reference Platform \(TERRA-REF\) project available for use with attribution. Each type of data will include or point to the appropriate attribution policy.

## Timing and Control of Release

We plan to release the data in stages or tiers. For pre-release access please complete the [alpha tester application](https://goo.gl/forms/YqeiFfCHQm4nUG6l2).

1. The **first tier** will be an internal release to the TERRA-REF team and the standards committee. This first tier release will be to initially quality check and calibrate the data and will take place as data sets are produced and compiled. 
   1. By November 2016, it is an objective of the TERRA-REF team to establish a data release pipeline, wherein the release of data to this first tier will be within 21 days from the date of collection.
   2. Access to the data will be arranged for by the resource producer \(i.e. limiting access to selected users\). 
2. The **second tier** will enable the release of the data generated solely by the TERRA-REF team to other TERRA teams as well as non-TERRA entities. 
   1. By November 2017, it is an objective of the TERRA-REF team to establish a data release pipeline, wherein the release of data to this second tier will be within 10 days from the data of collection. 
   2. It is noted that release of the data to the second tier may occur prior to publication and that access is granted with the understanding that the contributions and interests of the TERRA-REF team should be recognized and respected by the users of the data. The TERRA-REF team reserves the right to analyze and published its own data. Resource users should appropriately cite the source of the data and acknowledge the resource produces. The publication of the data, as suggested in the TERRA-REF Authorship Guidelines, should specify the collaborative nature of the project, and authorship is expected to include all those TERRA-REF team members contributing significantly to the work. 
3. Access to the data will be determined by the resource producers and may be governed by separate license or other agreements. 1. iii\)It is an objective of the TERRA-REF team to enable the release of the data to the public by November 2018 but no later than the date of close-out of the awarded funds.

## Genomic Data

### Restrictions on dataset usage

Genomic data for the _Sorghum bicolor_ Bioenergy Association Panel \(BAP\) from the TERRA-REF project is available pre-publication to maximize the community benefit of these resources. Use of the raw and processed data that is available should follow the principles of the [Fort Lauderdale Agreement](https://www.genome.gov/pages/research/wellcomereport0303.pdf) and the [Department of Energy's Joint Genome Institute \(JGI\) early release policies](http://genome.jgi.doe.gov/pages/data-usage-policy.jsf).

By accessing these data, you agree not to publish any articles containing analyses of genes or genomic data on a whole genome or chromosome scale prior to publication by TERRA-REF and/or its collaborators of a comprehensive genome analysis \("Reserved Analyses"\). "Reserved analyses" include the identification of complete \(whole genome\) sets of genomic features such as genes, gene families, regulatory elements, repeat structures, GC content, or any other genome feature, and whole-genome- or chromosome-scale comparisons with other species. The embargo on publication of Reserved Analyses by researchers outside of the TERRA-REF project is expected to extend until the publication of the results of the sequencing project is accepted. Scientific users are free to publish papers dealing with specific genes or small sets of genes using the sequence data. If these data are used for publication, the following acknowledgment should be included: 'These sequence data were produced by the US Department of Energy Transportation Energy Resources from Renewable Agriculture Phenotyping Reference Platform \(TERRA-REF\) Project'. These data may be freely downloaded and used by all who respect the restrictions in the previous paragraphs. The assembly and sequence data should not be redistributed or repackaged without permission from TERRA-REF. Any redistribution of the data during the embargo period should carry this notice: "The TERRA-REF project provides these data in good faith, but makes no warranty, expressed or implied, nor assumes any legal liability or responsibility for any purpose for which the data are used. Once the sequence is moved to unreserved status, the data will be freely available for any subsequent use."

We prefer that potential users of these sequence data contact the individuals listed under Contacts with their plans to ensure that proposed usage of sequence data are not considered Reserved Analyses.

## Software and Algorithms

For algorithms, we intend to release via BSD 3 clause or MIT / BSD compatible license.

## Images, Phenotypes, and Other Raw Data

For other raw data, such as phenotypic data and associated metadata, we intend to release data under [CC0: Creative Commons with No Rights Reserved - Public Domain)](https://creativecommons.org/share-your-work/public-domain/cc0/). This is to enable reuse of these data, but **Scientists are expected cite our data and research publications.** For more information, see related discussion and links in https://github.com/terraref/reference-data/issues/216.

## Contacts

Todd Mockler, Project/Genomics Lead (email: tmockler@danforthcenter.org)

David LeBauer, Computing Pipeline Lead (email: dlebauer@email.arizona.edu)

Nadia Shakoor, Project Director (email: nshakoor@danforthcenter.org)

